// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW8PmUFBNOIwS2dsrSBoSmeYYYm9440a4',
    appId: '1:852860472748:android:4e721cb6a267b2ae65fe09',
    messagingSenderId: '852860472748',
    projectId: 'we-chat-14c0f',
    storageBucket: 'we-chat-14c0f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8NmvPoTwy28qk_xtrm0kMfvF02T6BxEA',
    appId: '1:852860472748:ios:dd38147371efa4f665fe09',
    messagingSenderId: '852860472748',
    projectId: 'we-chat-14c0f',
    storageBucket: 'we-chat-14c0f.firebasestorage.app',
    iosBundleId: 'com.harshRajpurohit.weChat',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBTiEbU1cpDuFuWp0AwCsaBlUciptax88',
    appId: '1:852860472748:web:90f9a138e6376cbb65fe09',
    messagingSenderId: '852860472748',
    projectId: 'we-chat-14c0f',
    authDomain: 'we-chat-14c0f.firebaseapp.com',
    storageBucket: 'we-chat-14c0f.firebasestorage.app',
    measurementId: 'G-9DNPRLZD2P',
  );

}